import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { mkdirSync, writeFileSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import pg from "pg";
import { run, check } from "../src/internals/_pipeline.js";

const DATABASE_URL = "postgresql://appuser:secret@localhost:5432/sqlove_test";
const TMP = join(tmpdir(), `sqlove-pipeline-${Date.now()}`);

beforeAll(async () => {
  // Ensure schema
  const client = new pg.Client({ connectionString: DATABASE_URL });
  await client.connect();
  await client.query(`
    CREATE TABLE IF NOT EXISTS todo (
      id serial PRIMARY KEY,
      title text NOT NULL,
      description text,
      done boolean NOT NULL DEFAULT false,
      created_at timestamptz NOT NULL DEFAULT now(),
      completed_at timestamptz
    );
    DO $$ BEGIN
      CREATE TYPE todo_priority AS ENUM ('low', 'medium', 'high', 'urgent');
    EXCEPTION WHEN duplicate_object THEN null;
    END $$;
    ALTER TABLE todo ADD COLUMN IF NOT EXISTS priority todo_priority NOT NULL DEFAULT 'medium';
  `);
  await client.end();

  // Build fixture src/
  mkdirSync(join(TMP, "src/app/sql"), { recursive: true });
  writeFileSync(
    join(TMP, "src/app/sql/list_todos.sql"),
    "-- List all todos.\nSELECT id, title, priority FROM todo ORDER BY title"
  );
  writeFileSync(
    join(TMP, "src/app/sql/find_todo.sql"),
    "-- Find by title.\nSELECT id, title, description FROM todo WHERE title = $1"
  );
  writeFileSync(
    join(TMP, "src/app/sql/delete_todo.sql"),
    "DELETE FROM todo WHERE id = $1"
  );

  process.env["DATABASE_URL"] = DATABASE_URL;
});

afterAll(() => {
  rmSync(TMP, { recursive: true, force: true });
  delete process.env["DATABASE_URL"];
});

describe("pipeline end-to-end", () => {
  it("generates a sql.ts file from sql/ directory", async () => {
    const result = await run(join(TMP, "src"));

    expect(result.errors).toHaveLength(0);
    expect(result.modules).toHaveLength(1);
    expect(result.written).toHaveLength(1);
    expect(result.written[0]).toContain(join("app", "sql.ts"));

    const content = readFileSync(result.written[0]!, "utf8");
    expect(content).toContain("Auto-generated by sqlove");
  });

  it("generated file contains all queries", async () => {
    const outPath = join(TMP, "src/app/sql.ts");
    const content = readFileSync(outPath, "utf8");

    // All three queries present
    expect(content).toContain("listTodos");
    expect(content).toContain("findTodo");
    expect(content).toContain("deleteTodo");
  });

  it("is idempotent — second run writes nothing", async () => {
    const result = await run(join(TMP, "src"));
    expect(result.written).toHaveLength(0);
  });

  it("check mode passes after generate", async () => {
    const result = await check(join(TMP, "src"));
    expect(result.ok).toBe(true);
    expect(result.stale).toHaveLength(0);
  });

  it("check mode detects drift when file is modified", async () => {
    const outPath = join(TMP, "src/app/sql.ts");
    writeFileSync(outPath, "// tampered");

    const result = await check(join(TMP, "src"));
    expect(result.ok).toBe(false);
    expect(result.stale).toHaveLength(1);

    // Restore
    await run(join(TMP, "src"));
  });

  it("survives a bad query alongside good ones", async () => {
    writeFileSync(
      join(TMP, "src/app/sql/bad_query.sql"),
      "SELECT FROM WHERE NOPE"
    );

    const result = await run(join(TMP, "src"));

    // Error collected
    expect(result.errors.length).toBeGreaterThan(0);
    expect(result.errors.some((e) => e._tag === "IntrospectionError")).toBe(true);

    // Good queries still in the output
    const content = readFileSync(join(TMP, "src/app/sql.ts"), "utf8");
    expect(content).toContain("listTodos");
    expect(content).toContain("findTodo");

    // Cleanup
    rmSync(join(TMP, "src/app/sql/bad_query.sql"));
    await run(join(TMP, "src"));
  });
});
