// ============================================================
// Auto-generated by sqlove — do not edit.
// ============================================================

import { Effect } from "effect";
import * as Schema from "effect/Schema";
import type { SqlError } from "@effect/sql/SqlError";
import { SqlClient } from "@effect/sql/SqlClient";

// ---- Enums ----

/** Postgres enum `todo_priority` */
export const TodoPriority = Schema.Literal("low", "medium", "high", "urgent");
export type TodoPriority = typeof TodoPriority.Type;

/** Rows returned by {@link completeTodo}.
 *  @see `todos/sql/complete_todo.sql` */
export class CompleteTodoRow extends Schema.Class<CompleteTodoRow>("CompleteTodoRow")({
  id: Schema.Number,
  title: Schema.String,
  priority: TodoPriority,
  done: Schema.Boolean,
  completedAt: Schema.propertySignature(Schema.NullOr(Schema.DateFromString)).pipe(Schema.fromKey("completed_at")),
}) {}

/**
 * Mark a todo as done.
 * @see `todos/sql/complete_todo.sql`
 */
export const completeTodo = (
  params: {
    readonly id: number;
  }
): Effect.Effect<ReadonlyArray<CompleteTodoRow>, SqlError, SqlClient> =>
  SqlClient.pipe(Effect.flatMap((sql) =>
    sql<CompleteTodoRow>`UPDATE todo
SET done = true, completed_at = now()
WHERE id = ${params.id} AND done = false
RETURNING id, title, priority, done, completed_at`
  ));

/** Rows returned by {@link createTodo}.
 *  @see `todos/sql/create_todo.sql` */
export class CreateTodoRow extends Schema.Class<CreateTodoRow>("CreateTodoRow")({
  id: Schema.Number,
  title: Schema.String,
  priority: TodoPriority,
  done: Schema.Boolean,
  createdAt: Schema.propertySignature(Schema.DateFromString).pipe(Schema.fromKey("created_at")),
}) {}

/**
 * Create a new todo.
 * @see `todos/sql/create_todo.sql`
 */
export const createTodo = (
  params: {
    readonly title: string;
    readonly description: string | null;
    readonly priority: TodoPriority;
    readonly shareWith: string | null;
    readonly fido: string | null;
  }
): Effect.Effect<ReadonlyArray<CreateTodoRow>, SqlError, SqlClient> =>
  SqlClient.pipe(Effect.flatMap((sql) =>
    sql<CreateTodoRow>`INSERT INTO todo (title, description, priority, share_with, fido)
VALUES (${params.title}, ${params.description}, ${params.priority}::todo_priority, ${params.shareWith}, ${params.fido})
RETURNING id, title, priority, done, created_at`
  ));

/**
 * Delete a todo by id.
 * @see `todos/sql/delete_todo.sql`
 */
export const deleteTodo = (
  params: {
    readonly id: number;
  }
): Effect.Effect<void, SqlError, SqlClient> =>
  SqlClient.pipe(Effect.flatMap((sql) =>
    sql`DELETE FROM todo WHERE id = ${params.id}`.pipe(Effect.asVoid)
  ));

/** Rows returned by {@link findByTag}.
 *  @see `todos/sql/find_by_tag.sql` */
export class FindByTagRow extends Schema.Class<FindByTagRow>("FindByTagRow")({
  id: Schema.Number,
  title: Schema.String,
  priority: TodoPriority,
  tags: Schema.Array(Schema.String),
  done: Schema.Boolean,
}) {}

/**
 * Find todos that have a given tag.
 * @see `todos/sql/find_by_tag.sql`
 */
export const findByTag = (
  params: {
    readonly arg1: string;
  }
): Effect.Effect<ReadonlyArray<FindByTagRow>, SqlError, SqlClient> =>
  SqlClient.pipe(Effect.flatMap((sql) =>
    sql<FindByTagRow>`SELECT id, title, priority, tags, done
FROM todo
WHERE ${params.arg1} = ANY(tags)
ORDER BY created_at DESC`
  ));

/** Rows returned by {@link getTodo}.
 *  @see `todos/sql/get_todo.sql` */
export class GetTodoRow extends Schema.Class<GetTodoRow>("GetTodoRow")({
  id: Schema.Number,
  title: Schema.String,
  description: Schema.NullOr(Schema.String),
  priority: TodoPriority,
  done: Schema.Boolean,
  createdAt: Schema.propertySignature(Schema.DateFromString).pipe(Schema.fromKey("created_at")),
  completedAt: Schema.propertySignature(Schema.NullOr(Schema.DateFromString)).pipe(Schema.fromKey("completed_at")),
}) {}

/**
 * Get a single todo by id.
 * @see `todos/sql/get_todo.sql`
 */
export const getTodo = (
  params: {
    readonly id: number;
  }
): Effect.Effect<ReadonlyArray<GetTodoRow>, SqlError, SqlClient> =>
  SqlClient.pipe(Effect.flatMap((sql) =>
    sql<GetTodoRow>`SELECT id, title, description, priority, done, created_at, completed_at
FROM todo
WHERE id = ${params.id}`
  ));

/** Rows returned by {@link listByPriority}.
 *  @see `todos/sql/list_by_priority.sql` */
export class ListByPriorityRow extends Schema.Class<ListByPriorityRow>("ListByPriorityRow")({
  id: Schema.Number,
  title: Schema.String,
  priority: TodoPriority,
  done: Schema.Boolean,
  createdAt: Schema.propertySignature(Schema.DateFromString).pipe(Schema.fromKey("created_at")),
}) {}

/**
 * List todos filtered by priority.
 * @see `todos/sql/list_by_priority.sql`
 */
export const listByPriority = (
  params: {
    readonly priority: TodoPriority;
  }
): Effect.Effect<ReadonlyArray<ListByPriorityRow>, SqlError, SqlClient> =>
  SqlClient.pipe(Effect.flatMap((sql) =>
    sql<ListByPriorityRow>`SELECT id, title, priority, done, created_at
FROM todo
WHERE priority = ${params.priority}::todo_priority
ORDER BY created_at DESC`
  ));

/** Rows returned by {@link listOverdue}.
 *  @see `todos/sql/list_overdue.sql` */
export class ListOverdueRow extends Schema.Class<ListOverdueRow>("ListOverdueRow")({
  id: Schema.Number,
  title: Schema.String,
  priority: TodoPriority,
  dueDate: Schema.propertySignature(Schema.NullOr(Schema.DateFromString)).pipe(Schema.fromKey("due_date")),
}) {}

/**
 * List todos that are past their due date.
 * @see `todos/sql/list_overdue.sql`
 */
export const listOverdue: Effect.Effect<
  ReadonlyArray<ListOverdueRow>,
  SqlError,
  SqlClient
> = SqlClient.pipe(Effect.flatMap((sql) =>
  sql<ListOverdueRow>`SELECT id, title, priority, due_date
FROM todo
WHERE due_date < now()::date AND done = false
ORDER BY due_date`
));

/** Rows returned by {@link listTodos}.
 *  @see `todos/sql/list_todos.sql` */
export class ListTodosRow extends Schema.Class<ListTodosRow>("ListTodosRow")({
  id: Schema.Number,
  title: Schema.String,
  priority: TodoPriority,
  done: Schema.Boolean,
  createdAt: Schema.propertySignature(Schema.DateFromString).pipe(Schema.fromKey("created_at")),
}) {}

/**
 * List all todos, newest first.
 * @see `todos/sql/list_todos.sql`
 */
export const listTodos: Effect.Effect<
  ReadonlyArray<ListTodosRow>,
  SqlError,
  SqlClient
> = SqlClient.pipe(Effect.flatMap((sql) =>
  sql<ListTodosRow>`SELECT id, title, priority, done, created_at
FROM todo
ORDER BY created_at DESC`
));

/** Rows returned by {@link reopenTodo}.
 *  @see `todos/sql/reopen_todo.sql` */
export class ReopenTodoRow extends Schema.Class<ReopenTodoRow>("ReopenTodoRow")({
  id: Schema.Number,
  title: Schema.String,
  priority: TodoPriority,
  done: Schema.Boolean,
}) {}

/**
 * Reopen a completed todo.
 * @see `todos/sql/reopen_todo.sql`
 */
export const reopenTodo = (
  params: {
    readonly id: number;
  }
): Effect.Effect<ReadonlyArray<ReopenTodoRow>, SqlError, SqlClient> =>
  SqlClient.pipe(Effect.flatMap((sql) =>
    sql<ReopenTodoRow>`UPDATE todo
SET done = false, completed_at = null
WHERE id = ${params.id} AND done = true
RETURNING id, title, priority, done`
  ));

/** Rows returned by {@link stats}.
 *  @see `todos/sql/stats.sql` */
export class StatsRow extends Schema.Class<StatsRow>("StatsRow")({
  total: Schema.Number,
  done: Schema.Number,
  pending: Schema.Number,
}) {}

/**
 * Get todo stats: total, done, pending.
 * @see `todos/sql/stats.sql`
 */
export const stats: Effect.Effect<
  ReadonlyArray<StatsRow>,
  SqlError,
  SqlClient
> = SqlClient.pipe(Effect.flatMap((sql) =>
  sql<StatsRow>`SELECT
  count(*)::int AS total,
  count(*) FILTER (WHERE done)::int AS done,
  count(*) FILTER (WHERE NOT done)::int AS pending
FROM todo`
));
