/*
 * Pure function. Takes TypedQuery[], emits TypeScript.
 * No I/O, no DB — just string building.
 *
 * Output shape per module:
 *   imports (Effect, Schema, SqlClient, SqlError)
 *   enums   (Schema.Literal for each pg enum)
 *   per query:
 *     Schema.Class row type (if returns columns)
 *     const (no params) or function (has params)
 *
 * Key transforms:
 *   file name snake_case → camelCase function
 *   column snake_case → camelCase via Schema.fromKey
 *   param snake_case → camelCase in params object
 *   $N in SQL → ${params.camelName} in template
 *   nullable cols → Schema.NullOr(...)
 *   nullable params → T | null
 *   mutations without RETURNING → Effect<void>
 *
 * Queries sorted alphabetically. Deterministic output.
 */

import type { EnumDef, TypedQuery, GeneratedModule } from "./types.js";

const HEADER = `// ============================================================
// Auto-generated by sqlove — do not edit.
// ============================================================`;

/**
 * Generate a TypeScript module from typed queries.
 */
export function generate(
  outputPath: string,
  queries: TypedQuery[],
  enums: EnumDef[],
): GeneratedModule {
  const sorted = [...queries].sort((a, b) =>
    a.file.queryName.localeCompare(b.file.queryName),
  );

  const lines: string[] = [HEADER, ""];

  // ── Imports ──────────────────────────────────────────────────
  lines.push(`import { Effect } from "effect";`);
  lines.push(`import * as Schema from "effect/Schema";`);
  lines.push(`import type { SqlError } from "@effect/sql/SqlError";`);
  lines.push(`import { SqlClient } from "@effect/sql/SqlClient";`);
  lines.push("");

  // ── Enums ────────────────────────────────────────────────────
  const sortedEnums = [...enums].sort((a, b) => a.name.localeCompare(b.name));
  if (sortedEnums.length > 0) {
    lines.push("// ---- Enums ----");
    lines.push("");
    for (const e of sortedEnums) {
      lines.push(emitEnum(e));
      lines.push("");
    }
  }

  // ── Row types + functions ────────────────────────────────────
  for (const query of sorted) {
    const fnName = snakeToCamel(query.file.queryName);
    const typeName = capitalize(fnName) + "Row";

    if (!query.isMutation) {
      lines.push(emitRowClass(query, fnName, typeName));
      lines.push("");
    }

    lines.push(emitFunction(query, fnName, typeName));
    lines.push("");
  }

  return { outputPath, source: lines.join("\n"), queries: sorted };
}

// ── Enum ────────────────────────────────────────────────────────────────────

function emitEnum(e: EnumDef): string {
  const literals = e.variants.map((v) => `"${v}"`).join(", ");
  return [
    `/** Postgres enum \`${e.pgName}\` */`,
    `export const ${e.name} = Schema.Literal(${literals});`,
    `export type ${e.name} = typeof ${e.name}.Type;`,
  ].join("\n");
}

// ── Row class ───────────────────────────────────────────────────────────────

function emitRowClass(
  query: TypedQuery,
  fnName: string,
  typeName: string,
): string {
  const fields = query.columns.map((col) => {
    const schema = col.nullable
      ? `Schema.NullOr(${col.tsType.schema})`
      : col.tsType.schema;
    return `  ${col.name}: ${schema},`;
  });

  const displayPath = `${query.file.modulePath}/sql/${query.file.queryName}.sql`;
  return [
    `/** Rows returned by {@link ${fnName}}.`,
    ` *  @see \`${displayPath}\` */`,
    `export class ${typeName} extends Schema.Class<${typeName}>("${typeName}")({`,
    ...fields,
    `}) {}`,
  ].join("\n");
}

// ── Function / const ────────────────────────────────────────────────────────

function emitFunction(
  query: TypedQuery,
  fnName: string,
  typeName: string,
): string {
  const displayPath = `${query.file.modulePath}/sql/${query.file.queryName}.sql`;

  // JSDoc
  const jsdocLines: string[] = [];
  if (query.docComment) {
    for (const line of query.docComment.split("\n")) {
      jsdocLines.push(` * ${line}`);
    }
  } else {
    jsdocLines.push(` * Runs the \`${query.file.queryName}\` query.`);
  }
  jsdocLines.push(` * @see \`${displayPath}\``);
  const jsdoc = `/**\n${jsdocLines.join("\n")}\n */`;

  // Build the template literal SQL with ${params.name} interpolations
  const templateSql = sqlToTemplate(query.sql, query.params);

  if (query.isMutation) {
    return emitMutationFunction(fnName, jsdoc, templateSql, query);
  }

  if (query.params.length === 0) {
    return emitConstQuery(fnName, typeName, jsdoc, templateSql);
  }

  return emitParamQuery(fnName, typeName, jsdoc, templateSql, query);
}

function emitConstQuery(
  fnName: string,
  typeName: string,
  jsdoc: string,
  templateSql: string,
): string {
  return [
    jsdoc,
    `export const ${fnName}: Effect.Effect<`,
    `  ReadonlyArray<${typeName}>,`,
    `  SqlError,`,
    `  SqlClient`,
    `> = SqlClient.pipe(Effect.flatMap((sql) =>`,
    `  sql<${typeName}>\`${templateSql}\``,
    `));`,
  ].join("\n");
}

function emitParamQuery(
  fnName: string,
  typeName: string,
  jsdoc: string,
  templateSql: string,
  query: TypedQuery,
): string {
  const paramFields = query.params
    .map((p) => {
      const type = p.nullable
        ? `${p.tsType.tsAnnotation} | null`
        : p.tsType.tsAnnotation;
      return `    readonly ${p.name}: ${type}`;
    })
    .join(";\n");

  return [
    jsdoc,
    `export const ${fnName} = (`,
    `  params: {`,
    `${paramFields};`,
    `  }`,
    `): Effect.Effect<ReadonlyArray<${typeName}>, SqlError, SqlClient> =>`,
    `  SqlClient.pipe(Effect.flatMap((sql) =>`,
    `    sql<${typeName}>\`${templateSql}\``,
    `  ));`,
  ].join("\n");
}

function emitMutationFunction(
  fnName: string,
  jsdoc: string,
  templateSql: string,
  query: TypedQuery,
): string {
  if (query.params.length === 0) {
    return [
      jsdoc,
      `export const ${fnName}: Effect.Effect<void, SqlError, SqlClient> =`,
      `  SqlClient.pipe(Effect.flatMap((sql) =>`,
      `    sql\`${templateSql}\`.pipe(Effect.asVoid)`,
      `  ));`,
    ].join("\n");
  }

  const paramFields = query.params
    .map((p) => {
      const type = p.nullable
        ? `${p.tsType.tsAnnotation} | null`
        : p.tsType.tsAnnotation;
      return `    readonly ${p.name}: ${type}`;
    })
    .join(";\n");

  return [
    jsdoc,
    `export const ${fnName} = (`,
    `  params: {`,
    `${paramFields};`,
    `  }`,
    `): Effect.Effect<void, SqlError, SqlClient> =>`,
    `  SqlClient.pipe(Effect.flatMap((sql) =>`,
    `    sql\`${templateSql}\`.pipe(Effect.asVoid)`,
    `  ));`,
  ].join("\n");
}

// ── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Transform SQL with $N placeholders into template literal body
 * where $N becomes ${params.argN}.
 */
function sqlToTemplate(
  sql: string,
  params: readonly import("./types.js").ResolvedParam[],
): string {
  let result = sql.replace(/`/g, "\\`");

  // Replace $N (descending to avoid $1 matching inside $10)
  const sorted = [...params].sort((a, b) => b.index - a.index);
  for (const p of sorted) {
    result = result.replace(
      new RegExp(`\\$${p.index}(?!\\d)`, "g"),
      "${params." + p.name + "}",
    );
  }

  return result;
}

function snakeToCamel(s: string): string {
  return s.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
